{% set name = "arize" %}
{% set version = "8.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize-{{ version }}.tar.gz
  sha256: dfac8635164fc2707aaf1c42b4c637a8967a5fc6d683f233f83d7aaf602cf5c4

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

outputs:
  - name: {{ name|lower }}
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=2.0.0
        - openinference-semantic-conventions >=0.1.25,<1
        - opentelemetry-exporter-otlp-proto-common >=1.38.0
        - opentelemetry-exporter-otlp-proto-grpc >=1.38.0
        - opentelemetry-sdk >=1.38.0
        - opentelemetry-semantic-conventions >=0.43b0,<1
        - pandas >=2.0.0,<3
        - protobuf >=4.21.0,<7
        - pyarrow >=0.15.0
        - pydantic >=2,<3
        - python-dateutil >=2.8.2,<3
        - requests >=2.0.0,<3
        - requests-futures >=1.0.0,<2
        - tqdm >4,<5
        - typing-extensions >=4.7.1,<5
        - urllib3 >=2.1.0,<3
        - wrapt >=1.0.0,<2.0.0
    test:
      imports:
        - arize
      requires:
        - python {{ python_min }}

  - name: {{ name|lower }}-with-embeddings
    build:
      number: 0
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}
        - pillow >=8.4.0,<11
        - datasets >=2.8,<3,!=2.14.*
        - tokenizers >=0.13,<1
        - pytorch >=1.13,<3
        - transformers >=4.25,<5
    test:
      imports:
        - arize
        - arize.embeddings
      requires:
        - python {{ python_min }}

  - name: {{ name|lower }}-with-mimic
    build:
      number: 0
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}
        - interpret-community >=0.22.0,<1
        - lightgbm
    test:
      imports:
        - arize
        - arize.ml.surrogate_explainer.mimic
      requires:
        - python {{ python_min }}

about:
  home: https://arize.com
  summary: A helper library to interact with Arize AI APIs
  dev_url: https://github.com/Arize-ai/client_python
  doc_url: https://docs.arize.com/arize
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - zephyap
    - Shubh18s
    - fjcasti1
  feedstock-name: {{ name|lower }}
